using Azure.AI.TextAnalytics;

namespace SentimentAnalysis
{
    internal class SentimentCalculation
    {

        // Example method for detecting opinions text. 
        internal static void SentimentAnalysisWithOpinionMiningExample(TextAnalyticsClient client)
        {
            var englishDocuments = new List<string>
            {
                "Virtual Rehabilitation and Telerehabilitation SystemsMarket Analysis By Major Manufacturers and Competitive landscape 2024-2032 The report summarizes all the information collected and serves the customer's requirements. However, these market analyses help in understanding market growth at both global and regional levels.GestureTek Health, Brontes Processing, Motek Medical (DIH Medical Group), Virtualware Group, Motorika, Bridgeway Senior",
                "Virtualware reports revenues of €2.034 million and net profit of €199,164 in 1H2024 Seite 1 - 18.07.2024 BILBAO, Spain, July 18. - European Virtual Reality company Virtualware recorded revenues of €2. 034 million in the first half of 2024, a growth of 28. 09% over the same period last year. ... Unai Extremo, CEO of Virtualware, explained, The significant and continued growth we are exper ... Headquartered in Bilbao (Spain), Virtualware is a global pioneer in developing virtual reality ... Downgrade in 3 Wochen gestern 15:31 Virtualware's flagship product, VIROO, facilitates the adop ...",
                "Today and on Thur, join our online sessions https://www.thevrara.com/industry-committees for: *Energy - Intro to our new co-chair Zuriñe Hernandez (from Virtualware, ex: GE Hitachi Nuclear, GE Vernova, Gestamp, Idom) *Thur 11am EST Training - Creating AI + XR soft skill training *Thur 11:30am EST Retail - Digital Humans for Conventional Commerce in XR",
                "Virtual Reality Based Telerehabilitation System Market Research Report: Exploring Growth Prospects and Future Outlook 2030 The global Virtual Reality Based Telerehabilitation System market size is expected to reach US$ ... The market is mainly driven by the significant applications of Virtual Reality Based Telerehabi ... The expanding demands from the Hospitals, Care Homes, Home and Others, are propelling Virtual R ... Physical Rehabilitation, one of the segments analysed in this report, is projected to record % ... Growth ... essing    Motek Medical (DIH Medical Group)    Virtualware Group    Motorika    Bridgeway Senio ..",
                "Virtualware partners with INVIA Digital to Drive US Expansion of Enterprise VR Solutions Bilbao, Spain,  August 20, 2024. -VRARA Member Virtualware (EPA: MLVIR), the European leader in enterprise virtual reality, has ... This partnership will focus on automotive and industrial applications of VIROO, a VR platform d ... VIROO is a secure ISO 27001-certified enterprise virtual reality software platform that enables ... This partnership a ... ith INVIA Digital is a natural progression for Virtualware as we continue to push the boundarie ... — John Cunningham, President of Virtualware USA ...",
                "MASTER Matters – How the Open XR Platform Can Be Used for Content Creation The EU project MASTER is about unlocking the potential of xr technologies for industrial training. The project launches a new video series MASTER Matters. In this, the third episode we meet the Maria Madarieta from Virtualware in Bilbao who describes the Open XR platform that is the core of the MASTER project. Amongst other things, we hear about the technological objectives of the project and learn how the Open XR platform can be used for content creation for non-experts in XR! The use of robots in i",
            };
            var swedishDocuments = new List<string>
            {
                "INTERMAT: Full fart efter hektisk Steelwristsäsong Steelwrist bullade upp i sin Intermatmonter. Företaget har lanserat produkter som aldrig förr 2024 och det ville man visa upp i Paris.INTERMAT: Full fart efter hektisk Steelwristsäsong Steelwrist bullade upp i sin Intermatmonter....Paris. Karl Serneberg, marknadschef på Steelwrist, lyfter främst fram nya tiltrotatorserien, Steelwrists",
                "Kylan är här men det hindrar inte oss. Vi håller på som vanligt med diverse olika uppdrag, VA, kabeljobb, tjältining, mm❄️❄️❄️❄️🚜🇸🇪🇸🇪🚧🚦☀️🇸🇪 #göthbergsschakt #wackerneuson #onenordic #blomtorpsentreprenad #ew100 #steelwrist #steelwristofficial #khmaskinab #heatwork #maskinsystemab #klockhammar #örebro #sweden🇸🇪",
                "Asfaltsjustering 🤠🫱🏽‍🫲🏼🚜🚨🦾 #mittxaluminiumproffset #swedentruckmachines #hardworkingmachines #köragrävmaskinärlivet #billowentreptenadab #excavatoroperator #excavatorsunited #engcon_sweden #PhotoOfTheDay #mostlydiggers #volvoce_emea #loveyourvolvo #emasweden #volvotrucks #excavators #Motivation #excavator #göteneufo #FollowMe #serameko #steelwrist #trucking #Happy #bagger #volvo #Inspo ...",
                "Jakobs Maskin AB our newest premium NOX dealer in Sweden.. We wish you the best. Welcome in to the Kinshofer family. Www.Jakobsmaskin.se#kinshofer #nox #kinshofergroup #excavator #grävmaskin #återförsäljare #excavatorlife #borås #engcon #rotortilt #steelwrist #tiltrotator #dealer #takeuchi #volvogrävmaskin #wackerneuson #grävmaskinsredskap",
                "Testa den – du kommer bli förälskad i den!” 💚 Skickliga maskinoperatören och steelwrist-ambassadören Linus testar vår nya tiltrotator XTR20 på Svenska Maskinmässan. Kolla för att höra vad han tycker! Det var en ära att ha dig som demooperatör, Linus. Du gjorde ett fantastiskt jobb 🔥 #steelwrist #steelwristtiltrotator #tiltrotator #XTR20 #svenskamaskinmässan #steelwristambassador #excavatoroperator #excavators #skilledoperator #earthmoving #earthmovingefficiency #excavatorattachments",
                "I Stockholm arbetar Michael Järn med sin Hydrema MX16 och sin Steelwrist X20 tiltrotator. ”Jag är väldigt nöjd med den här tiltrotatorn, den fungerar klockrent och har hållit väldigt bra”. Han berättar att han tidigare hade en tiltrotator från Engcon, men efter att ha fått köra en större maskin med en Steelwrist är han nu helt säker på att det är Steelwrist han vill använda framöver. ”Det är framför ... Stort tack Michael, för att du ville dela med dig av dina erfarenheter med Steelwrist 💚",
            };
            var frenchDocuments = new List<string>
            {
                "Pilote auto qui délire Hello, Recherche le compas fluxgate qui doit être connecté au st4000. Et essaye de le démonter délicatement pour voir s'il n'est pas abîmé ou bloqué ou s'il n'y a pas un objet métallique à proximité qui pourrait l'influencer. Voici un schéma virtualware.nl[...]ompass/ Amicalement. FX",
                "Lleida.net annonce des pertes de 2,65 millions d'euros et une baisse de 20 % de ses ventes en 2023 Madrid, 29 avril - Lleida.net (BME:LLN) (EPA:ALLLN) (OTCQX:LLEIF) les ventes ont chuté de 20% en 2023 en raison de l'évolution négative de l'activité de l'entreprise en Amérique latine et du changement de tendance sur le marché des SMS.européenne, qui est notre marché naturel, a expliqué Sisco Sapena, le fondateur et PDG de l'entreprise.",
                "Agenda : à suivre aujourd'hui sur les marchés financiers INDICATEURS ECONOMIQUES : France : - Indice PMI manufacturier français final. (09h50) Etats-Unis : - Inscriptions hebdomadaires au chômage. (14h30) - Productivité préliminaire du ... Vicat : Paiement dividendes Virtualware : Assemblée générale annuelle",
                "Virtualware annonce (mlvir.pa) un chiffre d'affaires record de 4,52 millions d'euros en 2023, soit une augmentation de 40 % par Cet article a été publié le mercredi 24 janvier 2024 à 15:23 .Il fait partie de la Lire la suite Par : La rédaction Mercredi 24 janvier 2024 à 08:25 Virtualware annonce (mlvir.pa) un chiffre d'affaires record de... Bilbao, 24 janvier - La société européenne de réalité virtuelle Virtualware (MLVIR.PA) (EPA:MLVIR) a annoncé un chiffre d'affaires",
                "Nattvasen Wikipédia : À proposWikipédia : À propos : Wikipédia est une encyclopédie en ligne gratuite que n'importe qui peut modifier de bonne foi, et que des millions de personnes possèdent déjà. Le but de Wikipédia est de profiter aux lecteurs en contenant des informations sur toutes les branches de la connaissance. ... Il est réalisé par Mahesh Manjrekar et produit par Nana Patekar et Vishwas Joshi sous la bannière de Great Maratha Entertainment, Gajanan Chitra et Fincraft Media and Entertainment Pvt",
                "AVANT / APRÈS sur un Larson FinCraft 2011 ⚓ #SeaDek de couleur TERRA / BLACK avec design TEAK LINE 🔥 Avec #SEADEK, c'est satisfaction GARANTIE! 💯 📞 514-627-6885 📩 info@luxmarine.ca Contactez-nous pour une soumission 𝗚𝗥𝗔𝗧𝗨𝗜𝗧𝗘 ! #boating #boatlife #boat #sailing #opendeck #speedboat #yacht #cruiser #marine #seadekcanada #seadek #luxmarine #cmdproduitsnautiques #marineproducts #boatflooring",
            };
            var spanishDocuments = new List<string>
            {
                "Lleida.net (LLN): seguimiento de la acción - Rankia Lleida.net registró ventas por valor de 9,57 millones de euros en el primer semestre de este año, un 10% más que en el mismo periodo de 2023, según ha avanzado este martes la compañía de servicios tecnológicos en un comunicado. Este avance, que se sostiene a lo largo de la práctica totalidad de las línea de negocio de la empresa, es consecuencia de los cambios estructurales puestos en marcha por Lleida.net a finales del 2023 y principios del 2024, y que ya están consolidados dentro de la compañía. De i ...",
                "Sisco Sapena Noticias relacionadas Lleida.net promete que este año sí superará sus pérdidas Lleida.net, en reestructuración: ERE de 29 empleados en Lleida y Madrid y cierre de filiales en el extranjero Sisco Sapena Noticias relacionadas Lleida.net promete que este año sí superará sus pérdidas... La CNMV multa a Lleida.net con 200.000 euros por abuso de mercado",
                "Lleidanetworks Serveis Telemàtics S A : Participaciones significativas de Lleida.net a 30 de junio de 2024 (279 KB) 01 de julio 2024 a las 17:49 EN https://investors.lleida.net/docs/en/20240701_HRelev.pdf Madrid, 1 de julio de 2024 Conforme a lo previsto en el artículo 17 del Reglamento (UE) nº 596/2014 sobre abuso de mercado y en el artículo 227 del texto refundido de la Ley de Mercado de valores, ley 6/2023, de 17 de marzo, y disposiciones concordantes, así como en la Circular 3/2020 de BME Growth de BME MFT Equity sobre información a suministrar por Empresas en Expansión, por la presente LLEIDANETWORKS SERVEIS TELEMÀTICS S.A.: (en adelante Lleida.net, o la Sociedad o la Compañía) pone en su conocimiento la siguiente información que ha sido elaborada bajo la exclusiva responsabilidad del emisor y sus administradores",
                "Lleidanetworks Serveis Telemàtics S A : Checkpoint · Junio 2024 … los números continúan al alza en el mes de mayo El Trading Update , que acaba de publicarse, ha confirmado la tendencia operativa al alza desde el inicio de 2024. Creemos que esto es importante porque el mercado todavía no ha dado crédito neto a Lleida.net por ello (los resultados del 1T24 supusieron una...accionistas vendedores de InDenova y mantenidos por Lleida.net como Autocartera. Fuente: LLN, Checkpoint partners",
                "Lleida.net alcanza récord de ventas y beneficios en primer semestre con un Ebitda de 1,4 millones. El gigante tecnológico Lleida.net ha sorprendido al mercado al registrar ventas por valor de 9,57 millones de euros en el primer semestre de este año, lo que representa un aumento del 10% en comparación con el mismo periodo de 2023. Esta información fue dada a conocer en un comunicado emitido por la empresa este martes. Lleida.net alcanza récord de ventas y beneficios en primer...El gigante tecnológico Lleida.net ha sorprendido al mercado al registrar ventas por",
                "Estas son las 10 mejores herramientas para firmar documentos online de forma fácil y segura (2024) ADVERTISEMENT Y hecho de Poder firmar documentos online ofrece una gran cantidad de ventajas , como evitar moverse o incluso utilizar el correo ordinario, poniendo en riesgo los documentos. documentos, Firmafy, Get Sign Easy, KeepSolid Sign, Lleida.net, Logalty, OneSpan Sign, PandaDoc, RightSignature, Scrive, Signature, Signaturely, Significant, Viaf",
            };
            var germanDocuments = new List<string>
            {
                "Kazakhstan Stock Exchange will 13% der Anteile der Moscow Exchange zurückkaufen Die kasachische Börse hat am Freitag erklärt, dass sie Gespräche über den Rückkauf des 13,1%igen Anteils der Moskauer Börse an ihr führen will oder die MOEX dazu bringen will, diesen an Dritte zu verkaufen. Kazakhstan Stock Exchange will 13% der Anteile der Moscow Exchange zurückkaufen",
                "Russische Investmentgruppe ICT verkauft Polymetal-Anteil an omanisches Konsortium Die Investmentgesellschaft ICT Holding, die dem russischen Geschäftsmann Alexander Nesis gehört, hat ihren Anteil von 23,9% am Gold- und Silberproduzenten Polymetal International an ein von der omanischen Regierung geführtes Konsortium verkauft, teilte Polymetal am Montag in einer Erklärung mit. von Jersey nach Kasachstan verlegt und ist an der Astana International Exchange (AIX) des zentralasiatischen Landes notiert, nachdem",
                "Virtuelle Realität (VR) in der Telerehabilitation Marktanalyse: Wettbewerbsumfeld, Wachstumsfaktoren, Umsatz | Motek Medical, Ge [Berlin, Apr 2024] — Ein bahnbrechender Marktforschungsbericht zum Thema Virtuelle Realität (VR) in der Telerehabilitation Markt wurde veröffentlicht Medical, GestureTek Health, Virtualware Group, Motorika [Berlin, Apr 2024] — Ein... • Motek Medical • GestureTek Health • Virtualware Group • Motorika • Bridgeway Senior Healthcare",
                "Augmented Reality für den Einzelhandelsmarkt – eine umfassende Studie von Hauptakteuren: Contus, Inde, Apphitect„ Global Market Vision hat kürzlich einen neuen Titel zum Augmented Reality für den Einzelhandel Market 2023 eingeführt und prognostiziert 2030 aus seiner Datenbank.Contus, Inde, Apphitect, Valuecoders, Intellectsoft, Xenium Digital, Virtualware Augmented Reality für den Einzelhandel Markt nach Typ:",
                "Augmented Reality für den Einzelhandelsmarkt wird in den kommenden Jahren 2023-2030 weltweit das höchste Wachstum verzeichnen Der Global Augmented Reality für den Einzelhandel -Marktbericht wurde unter Berücksichtigung aller zwingenden Teile der Marktforschung geplant, die Contus, Inde, Apphitect, Valuecoders, Intellectsoft, Xenium Digital, Virtualware Der Bericht befasst sich eingehend mit allen Marktrisiken und -chancen.",
                "Virtuelle Rehabilitationssysteme Marktgröße, Umfang und prognostiziertes Wachstum, neue Updates, Geschäftsausweitung und globale Weltweiter Virtuelle Rehabilitationssysteme Markt Der Forschungsbericht gibt einen detaillierten Überblick über die aktuelle Marktsituation und -prognose. Die Studie ist vielleicht eine perfekte Mischung aus qualitativen und quantitativen Informationen, die wichtige Marktentwicklungen, Herausforderungen, Analysen der Wettbewerbsbranche und neue Möglichkeiten und Trends auf dem Virtuelle Rehabilitationssysteme-Markt hervorhebt. Darüber hinaus enthält dieser Bericht Virtuel ... Virtualware Gruppe ...",
            };
            var dutchDocuments = new List<string>
            {
                "Galapagos: Cash met korting Galapagos gaat de tering naar de nering zetten. De financiële huishouding moet op orde want er stroomt te veel geld uit in verhouding tot de pijplijn. Galapagos heeft weliswaar een enorme zak met geld klaarstaan (€5,1 miljard, gedeeld door 65,5 mln aandelen is dat per aandeel €77,84) maar een deel van dat geld is nodig voor doorontwikkeling en uitrol van Jyseleca in Europa en een deel is nodig voor de rest van de pijplijn.Galapagos: Cash met korting Galapagos gaat de tering naar de nering zetten....te veel geld uit in verhouding tot de pijplijn. Galapagos heeft weliswaar een enorme zak met geld klaarstaan (€5,1",
                "Houdt Gilead belang in Galapagos aan?Galapagos kwam met een noodmelding gisteravond. De Amerikaanse toezichthouder FDA heeft in een nieuw gesprek met Gilead (Type A meeting heet zoiets) laten doorschemeren dat goedkeuring van Filgotinib in de VS weinig kans van slagen heeft.Houdt Gilead belang in Galapagos aan? Galapagos kwam met een noodmelding gisteravond.... Een aantal onderzoeksprogramma's worden stopgezet, zoals naar de werking van filgotinib bij psioriasis. Wel wordt onderzoek naar de werking",
                "RBC verlaagt koersdoel Galapagos (ABM FN-Dow Jones) RBC heeft het koersdoel op Galapagos verlaagd van 35,00 naar 32,00 dollar met een ongewijzigd Sectorperform, oftewel neutraal advies. Dit bleek vrijdg uit een analistenrapport van de Canadese bank.RBC verlaagt koersdoel Galapagos (ABM FN-Dow Jones) RBC heeft het koersdoel op Galapagos verlaagd van 35,00 naar 32,00 dollar met een...toezichthouder FDA aangaande de CAR-T productie. Galapagos kwam donderdag nabeurs met halfjaarcijfers, waarbij",
                "Galapagos handhaaft cashburn richtlijn (ABM FN-Dow Jones) Galapagos heeft de verwachte cashburn voor het lopende jaar gehandhaafd, terwijl de R&D-kosten in de eerste jaarhelft van 2024 stegen. Dit bleek donderdag nabeurs uit de resultaten van het Belgisch-Nederlandse biotechbedrijf.Galapagos handhaaft cashburn richtlijn (ABM FN-Dow Jones) Galapagos heeft de verwachte cashburn voor het lopende jaar...Dit bleek donderdag nabeurs uit de resultaten van het Belgisch-Nederlandse biotechbedrijf. NU 3 MAANDEN VOOR SLECHTS €24,95!",
                "Bel20 vindt het groen onder aanvoering van Aedifica en KBC (ABM FN) De Brusselse beurs beleeft maandagmiddag een saaie sessie, waarbij de Bel20 om half drie 0,1 procent won en op 3.836 punten noteerde.procent, gevolgd door KBC, dat 1,4 procent won. Galapagos, dat bij de opening ongeveer zeven procent ...steeg, noteerde nog maar 0,9 procent hoger. Het biotechbedrijf zal naar eigen zeggen bemoedigende nieuwe resultaten",
                "Galapagos presenteert bemoedigende nieuwe resultaten voor CD19 CAR-T kandidaat GLPG5101 in non-Hodgkin lymfoom op EHA 2024 Mechelen, België; 14 juni 2024, 22:01 CET; Galapagos NV (Euronext & NASDAQ: GLPG) kondigde vandaag aan dat het bemoedigende nieuwe resultaten zal presenteren van de lopende fase 1/2 ATALANTA-1 studie van CD19 CAR-T kandidaat, GLPG5101, in recidief/refractair non-Hodgkin lymfoom (R/R NHL) op het jaarlijkse European Hematology Association (EHA) 2024 hybride congres. Galapagos' productkandidaat GLPG5101 wordt geproduceerd met behulp van het innovatieve, gedecentraliseerde T-celproductieplatform van Galapagos.\r\nEHA 2024 Mechelen, België; 14 juni 2024, 22:01 CET; Galapagos NV (Euronext & NASDAQ: GLPG) kondigde vandaag aan...Hematology Association (EHA) 2024 hybride congres. Galapagos' productkandidaat GLPG5101 wordt geproduceerd met",
            };
            var finnishDocuments = new List<string>
            {
                "KLIKKAA TÄSTÄ JA KATSO 26. 1. ERIKOISLÄHETYS KUOPION KONEPÄIVILTÄ! Ammattilehti on tuottanut viikottaisen uutislähetyksen jo 194. perjantaina peräkkäin tarjoten kuljetus-, maarakennus- ja metsäalan tuoreimmat kuulumiset. Lähetyksen sisältö, vko 4 (kesto yhteensä 01:16:55): 00:00 Kuopion Konepäivät starttasi aurinkoisissa merkeissä 01:09 Avesco esitteli CAT koneet ja uuttakin edustusta tulossa 07:05 ... 01:05:43 Steelwrist tiltit ja lisävarusteet yhä useamman laatuvalinta ...",
                "Engconin valumetallisen ec219 s60 valumetalli alakerran purku ja halkeamien laajuuden toteaminen . Pari kertaa oli jo yritetty korjata ja jännitykset halkaisseet laajemmin niin iso työ korjata ja uuden alakerran löysi suomen erikoishuollon Mäkipää 2500e niin vanha ei jatkoon . Yhteistyössä Suomen erikoishuollon kanssa , josta saa avun kaikkiin pyörittäjä ongelmiin ja muuhunkin nyt purku ja kasaus työmaalla 👊🏻. #iloirtimaansiirtotekniikasta #päivystys #hitsaus #welding #iloirtiduunista #maastohitsaus #",
                "KATSO TÄSTÄ 7. 6. LÄHETYS! Ammattilehti on tuottanut viikoittaisen uutislähetyksen jo 215. perjantaina peräkkäin tarjoten kuljetus-, maarakennus- ja metsäalan tuoreimmat kuulumiset. Lähetyksen sisältö, vko 24 (kesto yhteensä 58:20): 00:00 Tervetuloa uutislähetykseen - juontajana Siiri Koivula METSÄALA: 00:36 John Deeren uudet H-sarjan metsäkoneet työnäytöskierroksella 13:11 Sampo-R ... 53:11 Steelwrist on yksi Ruotsin parhaiten johdettuja yrityksiä jo viidettä kertaa ...",
                "Eihän se ole Mörinä eikä mikään ilman Dynasetiä! 🔥 Vielä ehtii klo 15 asti tutustumaan uudistuneeseen uppopumppusarjaan! Mörinät käynnissä tänään lauantaina 13. 4. klo 9-15. Tervetuloa tutustumaan tuotteisiin ja palveluihimme! TAPAHTUMAN TIEDOT: Realparkinkatu 9-13, 37570 Lempäälä Perjantai 12. 4. klo 9 -17 Lauantai 13. 4. klo 9-15 Tapahtuma on ilmainen ja avoin kaikille. MUKANA M ... Finfinet, Geotrim, Steelwrist, Rototilt, VTR-Workware, ...",
                "Turun Villi Länsi rantautuu toimipisteellemme tällä viikolla! Eteläkaari 10:ssä on esillä laaja kattaus koneita maanrakennukseen, kiinteistönhoitoon ja maatalouteen! 🤩 Esillä muun muassa: - Develonin pyöräalustainen DX100W-7 kaivinkone - DX55R-7 minikaivukone sekä DX235LCR-7 ja DX350LC-7 tela-alustaiset kaivukoneet. - John Deere 6R 150, 6R 185, 6R 215, 6R 250 ... Lisäksi paikanpäällä yhteistyökumppanimme, muun muassa Steelwrist Suomi-Finland, Geotrim, SKF, Vama sekä Finfinet. ...",
                "Kuopion perinteiset konepäivät pidetään tämän viikon perjantaina ja lauantaina! Asentajankujalla RealMachineryn ja Wihuri Teknisen Kaupan toimipisteillä onkin paljon nähtävää ja koettavaa, kun esillä on täyden palvelun valikoima niin koneista kuin jälkimarkkinointi- ja konevuokrauspalvekuistamme. Esillä muun muassa Develon DX210W-7 pyöräalusatinen kaivinkone sekä DL220-7 pyörä ... Paikan päällä myös näytteilleasettajina Jussi Mantsinen MoToKo, Steelwrist, SKF, Trafino, FinFinet, Lametal Stark. ...",
            };

            AnalyzeSentimentResultCollection reviews = client.AnalyzeSentimentBatch(englishDocuments, options: new AnalyzeSentimentOptions()
            {
                IncludeOpinionMining = true,
            });

            foreach (AnalyzeSentimentResult review in reviews)
            {
                Console.WriteLine($"Document sentiment: {review.DocumentSentiment.Sentiment}\n");
                Console.WriteLine($"\tPositive score: {review.DocumentSentiment.ConfidenceScores.Positive:0.00}");
                Console.WriteLine($"\tNegative score: {review.DocumentSentiment.ConfidenceScores.Negative:0.00}");
                Console.WriteLine($"\tNeutral score: {review.DocumentSentiment.ConfidenceScores.Neutral:0.00}\n");
                Console.WriteLine($"\n");
            }
        }

    }
}
